In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
movies = pd.read_csv(r"The Data\movies.csv", nrows=5000, encoding="utf-8")
credit = pd.read_csv(r"The Data\credits.csv")

In [3]:
movies.head()

,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,revenue,runtime,status,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations
0,631842,Knock at the Cabin,Horror-Mystery-Thriller,en,While vacationing at a remote cabin a young gi...,3422.537,Blinding Edge Pictures-Universal Pictures-Film...,2023-02-01,20000000.0,52000000.0,100.0,Released,Save your family or save humanity. Make the ch...,6.457,888.0,Dave Bautista-Jonathan Groff-Ben Aldridge-Kris...,based on novel or book-sacrifice-cabin-faith-e...,/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg,/zWDMQX0sPaW2u0N2pJaYA8bVVaJ.jpg,1058949-646389-772515-505642-143970-667216-104...
1,646389,Plane,Action-Adventure-Thriller,en,After a heroic job of successfully landing his...,2618.646,MadRiver Pictures-Di Bonaventura Pictures-G-BA...,2023-01-12,25000000.0,51000000.0,107.0,Released,Survive together or die alone.,6.901,785.0,Gerard Butler-Mike Colter-Yoson An-Tony Goldwy...,pilot-airplane-philippines-held hostage-plane ...,/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg,/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg,505642-758769-864692-631842-1058949-925943-758...
2,315162,Puss in Boots: The Last Wish,Animation-Adventure-Comedy-Family,en,Puss in Boots discovers that his passion for a...,2589.341,DreamWorks Animation-Universal Pictures,2022-12-07,90000000.0,442000000.0,103.0,Released,Say hola to his little friends.,8.402,4357.0,Antonio Banderas-Salma Hayek-Harvey Guillén-Wa...,fairy tale-talking dog-spin off-aftercreditsst...,/kuf6dutpsT0vSVehic3EZIqkOBt.jpg,/b1Y8SUb12gPHCSSSNlbX4nB3IKy.jpg,536554-76600-816904-653851-899112-985335-83078...
3,505642,Black Panther: Wakanda Forever,Action-Adventure-Science Fiction,en,Queen Ramonda Shuri M’Baku Okoye and the Dora ...,2525.408,Marvel Studios,2022-11-09,250000000.0,858535561.0,162.0,Released,Forever.,7.338,3922.0,Letitia Wright-Lupita Nyong'o-Danai Gurira-Win...,loss of loved one-hero-sequel-superhero-based ...,/sv1xJUazXeYqALzczSZ3O6nkH75.jpg,/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg,436270-829280-76600-56969-312634-1037858-238-5...
4,956101,The Eighth Clause,Thriller,la,Kat and Borja appear to be a perfect couple bu...,2259.303,SDB Films-El Hombre Orquesta,2022-04-29,0.0,0.0,0.0,Released,NaN,4.600,10.0,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,NaN,/8tc8eMFAX2SDC1TRu987qFQy8Cl.jpg,/kLnqNE9Af5QHyvUxw8cDGhF1ilv.jpg,NaN

In [4]:
"https://image.tmdb.org/t/p/w500/"+movies[movies["id"]==19995]["poster_path"]

38    https://image.tmdb.org/t/p/w500//jRXYjXNq0Cs2T...
Name: poster_path, dtype: object

In [5]:
movies.columns

Index(['id', 'title', 'genres', 'original_language', 'overview', 'popularity',
       'production_companies', 'release_date', 'budget', 'revenue', 'runtime',
       'status', 'tagline', 'vote_average', 'vote_count', 'credits',
       'keywords', 'poster_path', 'backdrop_path', 'recommendations'],
      dtype='object')

In [6]:
#  genres
# title
# id
# overview
# credits
# keywords

In [7]:
mid = movies.id
mid

0       631842
1       646389
2       315162
3       505642
4       956101
         ...
4995       123
4996     30636
4997       793
4998     11021
4999    706774
Name: id, Length: 5000, dtype: int64

In [8]:
credit[credit["movie_id"].isin(mid)]

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...
4602,389,12 Angry Men,"[{""cast_id"": 29, ""character"": ""Juror 8"", ""cred...","[{""credit_id"": ""52fe423dc3a36847f800ec55"", ""de..."
4670,9659,Mad Max,"[{""cast_id"": 1, ""character"": ""Mad Max Rockatan...","[{""credit_id"": ""52fe4517c3a36847f80bc035"", ""de..."
4672,391,A Fistful of Dollars,"[{""cast_id"": 1, ""character"": ""Joe"", ""credit_id...","[{""credit_id"": ""52fe423dc3a36847f800edd3"", ""de..."
4722,18925,Facing the Giants,"[{""cast_id"": 2, ""character"": ""Matt Prater"", ""c...","[{""credit_id"": ""52fe47ab9251416c750a178d"", ""de..."
4738,473,Pi,"[{""cast_id"": 5, ""character"": ""Maximillian Cohe...","[{""credit_id"": ""52fe4247c3a36847f8011f69"", ""de..."

In [9]:
movies.loc[movies["id"].isin(mid), "cast"] = credit['cast']
movies.loc[movies["id"].isin(mid), "crew"] = credit['crew']

In [10]:
movies[movies["title"]=="Avatar"]

,id,title,genres,original_language,overview,popularity,production_companies,release_date,budget,revenue,...,tagline,vote_average,vote_count,credits,keywords,poster_path,backdrop_path,recommendations,cast,crew
38,19995,Avatar,Action-Adventure-Fantasy-Science Fiction,en,In the 22nd century a paraplegic Marine is dis...,521.164,Dune Entertainment-Lightstorm Entertainment-20...,2009-12-15,237000000.0,2.920357e+09,...,Enter the world of Pandora.,7.567,28557.0,Sam Worthington-Zoe Saldaña-Sigourney Weaver-S...,culture clash-future-space war-space colony-so...,/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,1010821-773867-572261-24428-70160-49051-49026-...,"[{""cast_id"": 3, ""character"": ""Peter Parker / S...","[{""credit_id"": ""53e66a1cc3a3684439001575"", ""de..."

In [11]:
movies_df = movies[["id", "title", "genres", "overview", "credits", "keywords", "cast", "crew"]]

In [12]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew
0,631842,Knock at the Cabin,Horror-Mystery-Thriller,While vacationing at a remote cabin a young gi...,Dave Bautista-Jonathan Groff-Ben Aldridge-Kris...,based on novel or book-sacrifice-cabin-faith-e...,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,646389,Plane,Action-Adventure-Thriller,After a heroic job of successfully landing his...,Gerard Butler-Mike Colter-Yoson An-Tony Goldwy...,pilot-airplane-philippines-held hostage-plane ...,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,315162,Puss in Boots: The Last Wish,Animation-Adventure-Comedy-Family,Puss in Boots discovers that his passion for a...,Antonio Banderas-Salma Hayek-Harvey Guillén-Wa...,fairy tale-talking dog-spin off-aftercreditsst...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,505642,Black Panther: Wakanda Forever,Action-Adventure-Science Fiction,Queen Ramonda Shuri M’Baku Okoye and the Dora ...,Letitia Wright-Lupita Nyong'o-Danai Gurira-Win...,loss of loved one-hero-sequel-superhero-based ...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,956101,The Eighth Clause,Thriller,Kat and Borja appear to be a perfect couple bu...,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,NaN,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,Adventure-Animation-Fantasy,The Fellowship of the Ring embark on a journey...,Christopher Guard-William Squire-Michael Schol...,elves-dwarf-based on novel or book-mission,NaN,NaN
4996,30636,Luna,Drama,While touring in Italy a recently-widowed Amer...,Jill Clayburgh-Matthew Barry-Veronica Lazăr-Re...,italy-parent child relationship-heroin-diva-wi...,NaN,NaN
4997,793,Blue Velvet,Drama-Crime-Mystery-Thriller,The discovery of a severed human ear found in ...,Kyle MacLachlan-Isabella Rossellini-Dennis Hop...,sexual obsession-detective-small town-drug dea...,NaN,NaN
4998,11021,Titanic,Action-Drama-History,This little-known German film retells the true...,Sybille Schmitz-Hans Nielsen-Kirsten Heiberg-K...,sea-captain-passenger-cruise-iceberg-titanic-s...,NaN,NaN
4999,706774,Hope of Breast,Romance,Yoshikawa Aimi refused to sleep with her husba...,Aimi Yoshikawa,softcore,NaN,NaN

In [13]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        5000 non-null   int64
 1   title     5000 non-null   object
 2   genres    4934 non-null   object
 3   overview  4938 non-null   object
 4   credits   4907 non-null   object
 5   keywords  4267 non-null   object
 6   cast      4803 non-null   object
 7   crew      4803 non-null   object
dtypes: int64(1), object(7)
memory usage: 312.6+ KB

In [14]:
movies_df.isnull().sum()

id            0
title         0
genres       66
overview     62
credits      93
keywords    733
cast        197
crew        197
dtype: int64

In [15]:
movies_df.fillna("Random", inplace=True)

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\2242740441.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df.fillna("Random", inplace=True)

In [16]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew
0,631842,Knock at the Cabin,Horror-Mystery-Thriller,While vacationing at a remote cabin a young gi...,Dave Bautista-Jonathan Groff-Ben Aldridge-Kris...,based on novel or book-sacrifice-cabin-faith-e...,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,646389,Plane,Action-Adventure-Thriller,After a heroic job of successfully landing his...,Gerard Butler-Mike Colter-Yoson An-Tony Goldwy...,pilot-airplane-philippines-held hostage-plane ...,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,315162,Puss in Boots: The Last Wish,Animation-Adventure-Comedy-Family,Puss in Boots discovers that his passion for a...,Antonio Banderas-Salma Hayek-Harvey Guillén-Wa...,fairy tale-talking dog-spin off-aftercreditsst...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,505642,Black Panther: Wakanda Forever,Action-Adventure-Science Fiction,Queen Ramonda Shuri M’Baku Okoye and the Dora ...,Letitia Wright-Lupita Nyong'o-Danai Gurira-Win...,loss of loved one-hero-sequel-superhero-based ...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,956101,The Eighth Clause,Thriller,Kat and Borja appear to be a perfect couple bu...,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,Random,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,Adventure-Animation-Fantasy,The Fellowship of the Ring embark on a journey...,Christopher Guard-William Squire-Michael Schol...,elves-dwarf-based on novel or book-mission,Random,Random
4996,30636,Luna,Drama,While touring in Italy a recently-widowed Amer...,Jill Clayburgh-Matthew Barry-Veronica Lazăr-Re...,italy-parent child relationship-heroin-diva-wi...,Random,Random
4997,793,Blue Velvet,Drama-Crime-Mystery-Thriller,The discovery of a severed human ear found in ...,Kyle MacLachlan-Isabella Rossellini-Dennis Hop...,sexual obsession-detective-small town-drug dea...,Random,Random
4998,11021,Titanic,Action-Drama-History,This little-known German film retells the true...,Sybille Schmitz-Hans Nielsen-Kirsten Heiberg-K...,sea-captain-passenger-cruise-iceberg-titanic-s...,Random,Random
4999,706774,Hope of Breast,Romance,Yoshikawa Aimi refused to sleep with her husba...,Aimi Yoshikawa,softcore,Random,Random

In [17]:
movies_df.duplicated().sum()

0

In [18]:
movies_df["genres"] = movies_df["genres"].str.split('-')

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3236899499.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["genres"] = movies_df["genres"].str.split('-')

In [19]:
movies_df["keywords"] = movies_df["keywords"].str.split('-')

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3767724828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["keywords"] = movies_df["keywords"].str.split('-')

In [20]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew
0,631842,Knock at the Cabin,"[Horror, Mystery, Thriller]",While vacationing at a remote cabin a young gi...,Dave Bautista-Jonathan Groff-Ben Aldridge-Kris...,"[based on novel or book, sacrifice, cabin, fai...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,646389,Plane,"[Action, Adventure, Thriller]",After a heroic job of successfully landing his...,Gerard Butler-Mike Colter-Yoson An-Tony Goldwy...,"[pilot, airplane, philippines, held hostage, p...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,315162,Puss in Boots: The Last Wish,"[Animation, Adventure, Comedy, Family]",Puss in Boots discovers that his passion for a...,Antonio Banderas-Salma Hayek-Harvey Guillén-Wa...,"[fairy tale, talking dog, spin off, aftercredi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,505642,Black Panther: Wakanda Forever,"[Action, Adventure, Science Fiction]",Queen Ramonda Shuri M’Baku Okoye and the Dora ...,Letitia Wright-Lupita Nyong'o-Danai Gurira-Win...,"[loss of loved one, hero, sequel, superhero, b...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,956101,The Eighth Clause,[Thriller],Kat and Borja appear to be a perfect couple bu...,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,[Random],"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,"[Adventure, Animation, Fantasy]",The Fellowship of the Ring embark on a journey...,Christopher Guard-William Squire-Michael Schol...,"[elves, dwarf, based on novel or book, mission]",Random,Random
4996,30636,Luna,[Drama],While touring in Italy a recently-widowed Amer...,Jill Clayburgh-Matthew Barry-Veronica Lazăr-Re...,"[italy, parent child relationship, heroin, div...",Random,Random
4997,793,Blue Velvet,"[Drama, Crime, Mystery, Thriller]",The discovery of a severed human ear found in ...,Kyle MacLachlan-Isabella Rossellini-Dennis Hop...,"[sexual obsession, detective, small town, drug...",Random,Random
4998,11021,Titanic,"[Action, Drama, History]",This little-known German film retells the true...,Sybille Schmitz-Hans Nielsen-Kirsten Heiberg-K...,"[sea, captain, passenger, cruise, iceberg, tit...",Random,Random
4999,706774,Hope of Breast,[Romance],Yoshikawa Aimi refused to sleep with her husba...,Aimi Yoshikawa,[softcore],Random,Random

In [21]:
movies_df["cast"][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [22]:
ast.literal_eval('[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]')

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'character': 'Norm Spellman',
  'credit_id': '52fe48009251416c750ac9dd',
  'gender': 2,
  'id': 59231,
  'name': 'Joel David Moore',
  'order': 6},
 {'cast_id': 9,
  'character': 'Moat',
  'credit_id': '52fe48009251416c750ac9e5',
  'gender': 1,
  'id': 30485,
  'name': 'CCH Pounder',
  'order': 7},
 {'cast_id': 11,
  'character': 'Eytukan',
  'credit_id': '52fe48009251416c750ac9ed',
  'gender': 2,
  'id': 15853,
  'name': 'Wes Studi',
  'order': 8},
 {'cast_id': 10,
  'character': "Tsu'Tey",
  'credit_id': '52fe48009251416c750ac9e9',
  'gender': 2,
  'id': 10964,
  'name': 'Laz Alonso',
  'order': 9},
 {'cast_id': 12,
  'character': 'Dr. Max Patel',
  'credit_id': '52fe48009251416c750ac9f1',
  'gender': 2,
  'id': 95697,
  'name': 'Dileep Rao',
  'order': 10},
 {'cast_id': 13,
  'character': 'Lyle Wainfleet',
  'credit_id': '52fe48009251416c750ac9f5',
  'gender': 2,
  'id': 98215,
  'name': 'Matt Gerald',
  'order': 11},
 {'cast_id': 32,
  'character': 'Private Fike',
  'credit_id': '52fe48009251416c750aca5b',
  'gender': 2,
  'id': 154153,
  'name': 'Sean Anthony Moran',
  'order': 12},
 {'cast_id': 33,
  'character': 'Cryo Vault Med Tech',
  'credit_id': '52fe48009251416c750aca5f',
  'gender': 2,
  'id': 397312,
  'name': 'Jason Whyte',
  'order': 13},
 {'cast_id': 34,
  'character': 'Venture Star Crew Chief',
  'credit_id': '52fe48009251416c750aca63',
  'gender': 2,
  'id': 42317,
  'name': 'Scott Lawrence',
  'order': 14},
 {'cast_id': 35,
  'character': 'Lock Up Trooper',
  'credit_id': '52fe48009251416c750aca67',
  'gender': 2,
  'id': 986734,
  'name': 'Kelly Kilgour',
  'order': 15},
 {'cast_id': 36,
  'character': 'Shuttle Pilot',
  'credit_id': '52fe48009251416c750aca6b',
  'gender': 0,
  'id': 1207227,
  'name': 'James Patrick Pitt',
  'order': 16},
 {'cast_id': 37,
  'character': 'Shuttle Co-Pilot',
  'credit_id': '52fe48009251416c750aca6f',
  'gender': 0,
  'id': 1180936,
  'name': 'Sean Patrick Murphy',
  'order': 17},
 {'cast_id': 38,
  'character': 'Shuttle Crew Chief',
  'credit_id': '52fe48009251416c750aca73',
  'gender': 2,
  'id': 1019578,
  'name': 'Peter Dillon',
  'order': 18},
 {'cast_id': 39,
  'character': 'Tractor Operator / Troupe',
  'credit_id': '52fe48009251416c750aca77',
  'gender': 0,
  'id': 91443,
  'name': 'Kevin Dorman',
  'order': 19},
 {'cast_id': 40,
  'character': 'Dragon Gunship Pilot',
  'credit_id': '52fe48009251416c750aca7b',
  'gender': 2,
  'id': 173391,
  'name': 'Kelson Henderson',
  'order': 20},
 {'cast_id': 41,
  'character': 'Dragon Gunship Gunner',
  'credit_id': '52fe48009251416c750aca7f',
  'gender': 0,
  'id': 1207236,
  'name': 'David Van Horn',
  'order': 21},
 {'cast_id': 42,
  'character': 'Dragon Gunship Navigator',
  'credit_id': '52fe48009251416c750aca83',
  'gender': 0,
  'id': 215913,
  'name': 'Jacob Tomuri',
  'order': 22},
 {'cast_id': 43,
  'character': 'Suit #1',
  'credit_id': '52fe48009251416c750aca87',
  'gender': 0,
  'id': 143206,
  'name': 'Michael Blain-Rozgay',
  'order': 23},
 {'cast_id': 44,
  'character': 'Suit #2',
  'credit_id': '52fe48009251416c750aca8b',
  'gender': 2,
  'id': 169676,
  'name': 'Jon Curry',
  'order': 24},
 {'cast_id': 46,
  'character': 'Ambient Room Tech',
  'credit_id': '52fe48009251416c750aca8f',
  'gender': 0,
  'id': 1048610,
  'name': 'Luke Hawker',
  'order': 25},
 {'cast_id': 47,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48009251416c750aca93',
  'gender': 0,
  'id': 42288,
  'name': 'Woody Schultz',
  'order': 26},
 {'cast_id': 48,
  'character': 'Horse Clan Leader',
  'credit_id': '52fe48009251416c750aca97',
  'gender': 2,
  'id': 68278,
  'name': 'Peter Mensah',
  'order': 27},
 {'cast_id': 49,
  'character': 'Link Room Tech',
  'credit_id': '52fe48009251416c750aca9b',
  'gender': 0,
  'id': 1207247,
  'name': 'Sonia Yee',
  'order': 28},
 {'cast_id': 50,
  'character': 'Basketball Avatar / Troupe',
  'credit_id': '52fe48009251416c750aca9f',
  'gender': 1,
  'id': 1207248,
  'name': 'Jahnel Curfman',
  'order': 29},
 {'cast_id': 51,
  'character': 'Basketball Avatar',
  'credit_id': '52fe48009251416c750acaa3',
  'gender': 0,
  'id': 89714,
  'name': 'Ilram Choi',
  'order': 30},
 {'cast_id': 52,
  'character': "Na'vi Child",
  'credit_id': '52fe48009251416c750acaa7',
  'gender': 0,
  'id': 1207249,
  'name': 'Kyla Warren',
  'order': 31},
 {'cast_id': 53,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaab',
  'gender': 0,
  'id': 1207250,
  'name': 'Lisa Roumain',
  'order': 32},
 {'cast_id': 54,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acaaf',
  'gender': 1,
  'id': 83105,
  'name': 'Debra Wilson',
  'order': 33},
 {'cast_id': 57,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabb',
  'gender': 0,
  'id': 1207253,
  'name': 'Chris Mala',
  'order': 34},
 {'cast_id': 55,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab3',
  'gender': 0,
  'id': 1207251,
  'name': 'Taylor Kibby',
  'order': 35},
 {'cast_id': 56,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acab7',
  'gender': 0,
  'id': 1207252,
  'name': 'Jodie Landau',
  'order': 36},
 {'cast_id': 58,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acabf',
  'gender': 0,
  'id': 1207254,
  'name': 'Julie Lamm',
  'order': 37},
 {'cast_id': 59,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac3',
  'gender': 0,
  'id': 1207257,
  'name': 'Cullen B. Madden',
  'order': 38},
 {'cast_id': 60,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acac7',
  'gender': 0,
  'id': 1207259,
  'name': 'Joseph Brady Madden',
  'order': 39},
 {'cast_id': 61,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacb',
  'gender': 0,
  'id': 1207262,
  'name': 'Frankie Torres',
  'order': 40},
 {'cast_id': 62,
  'character': 'Troupe',
  'credit_id': '52fe48009251416c750acacf',
  'gender': 1,
  'id': 1158600,
  'name': 'Austin Wilson',
  'order': 41},
 {'cast_id': 63,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad3',
  'gender': 1,
  'id': 983705,
  'name': 'Sara Wilson',
  'order': 42},
 {'cast_id': 64,
  'character': 'Troupe',
  'credit_id': '52fe48019251416c750acad7',
  'gender': 0,
  'id': 1207263,
  'name': 'Tamica Washington-Miller',
  'order': 43},
 {'cast_id': 65,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadb',
  'gender': 1,
  'id': 1145098,
  'name': 'Lucy Briant',
  'order': 44},
 {'cast_id': 66,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acadf',
  'gender': 2,
  'id': 33305,
  'name': 'Nathan Meister',
  'order': 45},
 {'cast_id': 67,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae3',
  'gender': 0,
  'id': 1207264,
  'name': 'Gerry Blair',
  'order': 46},
 {'cast_id': 68,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acae7',
  'gender': 2,
  'id': 33311,
  'name': 'Matthew Chamberlain',
  'order': 47},
 {'cast_id': 69,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaeb',
  'gender': 0,
  'id': 1207265,
  'name': 'Paul Yates',
  'order': 48},
 {'cast_id': 70,
  'character': 'Op Center Duty Officer',
  'credit_id': '52fe48019251416c750acaef',
  'gender': 0,
  'id': 1207266,
  'name': 'Wray Wilson',
  'order': 49},
 {'cast_id': 71,
  'character': 'Op Center Staff',
  'credit_id': '52fe48019251416c750acaf3',
  'gender': 2,
  'id': 54492,
  'name': 'James Gaylyn',
  'order': 50},
 {'cast_id': 72,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaf7',
  'gender': 0,
  'id': 1207267,
  'name': 'Melvin Leno Clark III',
  'order': 51},
 {'cast_id': 73,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acafb',
  'gender': 0,
  'id': 1207268,
  'name': 'Carvon Futrell',
  'order': 52},
 {'cast_id': 74,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acaff',
  'gender': 0,
  'id': 1207269,
  'name': 'Brandon Jelkes',
  'order': 53},
 {'cast_id': 75,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb03',
  'gender': 0,
  'id': 1207270,
  'name': 'Micah Moch',
  'order': 54},
 {'cast_id': 76,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb07',
  'gender': 0,
  'id': 1207271,
  'name': 'Hanniyah Muhammad',
  'order': 55},
 {'cast_id': 77,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0b',
  'gender': 0,
  'id': 1207272,
  'name': 'Christopher Nolen',
  'order': 56},
 {'cast_id': 78,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb0f',
  'gender': 0,
  'id': 1207273,
  'name': 'Christa Oliver',
  'order': 57},
 {'cast_id': 79,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb13',
  'gender': 0,
  'id': 1207274,
  'name': 'April Marie Thomas',
  'order': 58},
 {'cast_id': 80,
  'character': 'Dancer',
  'credit_id': '52fe48019251416c750acb17',
  'gender': 0,
  'id': 1207275,
  'name': 'Bravita A. Threatt',
  'order': 59},
 {'cast_id': 81,
  'character': 'Mining Chief (uncredited)',
  'credit_id': '52fe48019251416c750acb1b',
  'gender': 0,
  'id': 1207276,
  'name': 'Colin Bleasdale',
  'order': 60},
 {'cast_id': 82,
  'character': 'Veteran Miner (uncredited)',
  'credit_id': '52fe48019251416c750acb1f',
  'gender': 0,
  'id': 107969,
  'name': 'Mike Bodnar',
  'order': 61},
 {'cast_id': 83,
  'character': 'Richard (uncredited)',
  'credit_id': '52fe48019251416c750acb23',
  'gender': 0,
  'id': 1207278,
  'name': 'Matt Clayton',
  'order': 62},
 {'cast_id': 84,
  'character': "Nav'i (uncredited)",
  'credit_id': '52fe48019251416c750acb27',
  'gender': 1,
  'id': 147898,
  'name': 'Nicole Dionne',
  'order': 63},
 {'cast_id': 85,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2b',
  'gender': 0,
  'id': 1207280,
  'name': 'Jamie Harrison',
  'order': 64},
 {'cast_id': 86,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb2f',
  'gender': 0,
  'id': 1207281,
  'name': 'Allan Henry',
  'order': 65},
 {'cast_id': 87,
  'character': 'Ground Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb33',
  'gender': 2,
  'id': 1207282,
  'name': 'Anthony Ingruber',
  'order': 66},
 {'cast_id': 88,
  'character': 'Flight Crew Mechanic (uncredited)',
  'credit_id': '52fe48019251416c750acb37',
  'gender': 0,
  'id': 1207283,
  'name': 'Ashley Jeffery',
  'order': 67},
 {'cast_id': 14,
  'character': 'Samson Pilot',
  'credit_id': '52fe48009251416c750ac9f9',
  'gender': 0,
  'id': 98216,
  'name': 'Dean Knowsley',
  'order': 68},
 {'cast_id': 89,
  'character': 'Trooper (uncredited)',
  'credit_id': '52fe48019251416c750acb3b',
  'gender': 0,
  'id': 1201399,
  'name': 'Joseph Mika-Hunt',
  'order': 69},
 {'cast_id': 90,
  'character': 'Banshee (uncredited)',
  'credit_id': '52fe48019251416c750acb3f',
  'gender': 0,
  'id': 236696,
  'name': 'Terry Notary',
  'order': 70},
 {'cast_id': 91,
  'character': 'Soldier (uncredited)',
  'credit_id': '52fe48019251416c750acb43',
  'gender': 0,
  'id': 1207287,
  'name': 'Kai Pantano',
  'order': 71},
 {'cast_id': 92,
  'character': 'Blast Technician (uncredited)',
  'credit_id': '52fe48019251416c750acb47',
  'gender': 0,
  'id': 1207288,
  'name': 'Logan Pithyou',
  'order': 72},
 {'cast_id': 93,
  'character': 'Vindum Raah (uncredited)',
  'credit_id': '52fe48019251416c750acb4b',
  'gender': 0,
  'id': 1207289,
  'name': 'Stuart Pollock',
  'order': 73},
 {'cast_id': 94,
  'character': 'Hero (uncredited)',
  'credit_id': '52fe48019251416c750acb4f',
  'gender': 0,
  'id': 584868,
  'name': 'Raja',
  'order': 74},
 {'cast_id': 95,
  'character': 'Ops Centreworker (uncredited)',
  'credit_id': '52fe48019251416c750acb53',
  'gender': 0,
  'id': 1207290,
  'name': 'Gareth Ruck',
  'order': 75},
 {'cast_id': 96,
  'character': 'Engineer (uncredited)',
  'credit_id': '52fe48019251416c750acb57',
  'gender': 0,
  'id': 1062463,
  'name': 'Rhian Sheehan',
  'order': 76},
 {'cast_id': 97,
  'character': "Col. Quaritch's Mech Suit (uncredited)",
  'credit_id': '52fe48019251416c750acb5b',
  'gender': 0,
  'id': 60656,
  'name': 'T. J. Storm',
  'order': 77},
 {'cast_id': 98,
  'character': 'Female Marine (uncredited)',
  'credit_id': '52fe48019251416c750acb5f',
  'gender': 0,
  'id': 1207291,
  'name': 'Jodie Taylor',
  'order': 78},
 {'cast_id': 99,
  'character': 'Ikran Clan Leader (uncredited)',
  'credit_id': '52fe48019251416c750acb63',
  'gender': 1,
  'id': 1186027,
  'name': 'Alicia Vela-Bailey',
  'order': 79},
 {'cast_id': 100,
  'character': 'Geologist (uncredited)',
  'credit_id': '52fe48019251416c750acb67',
  'gender': 0,
  'id': 1207292,
  'name': 'Richard Whiteside',
  'order': 80},
 {'cast_id': 101,
  'character': "Na'vi (uncredited)",
  'credit_id': '52fe48019251416c750acb6b',
  'gender': 0,
  'id': 103259,
  'name': 'Nikie Zambo',
  'order': 81},
 {'cast_id': 102,
  'character': 'Ambient Room Tech / Troupe',
  'credit_id': '52fe48019251416c750acb6f',
  'gender': 1,
  'id': 42286,
  'name': 'Julene Renee',
  'order': 82}]

In [23]:
def convertCast(obj):
    if obj == np.nan or obj == "Random":
        return list(("Random",))
    else:
        l = []
        counter = 0
        for i in ast.literal_eval(obj):
            if counter != 3:
                l.append(i["name"])
                counter += 1
            else:
                break
        return l

In [24]:
movies_df["cast"]=movies_df["cast"].apply(convertCast)

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\1923564671.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["cast"]=movies_df["cast"].apply(convertCast)

In [25]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew
0,631842,Knock at the Cabin,"[Horror, Mystery, Thriller]",While vacationing at a remote cabin a young gi...,Dave Bautista-Jonathan Groff-Ben Aldridge-Kris...,"[based on novel or book, sacrifice, cabin, fai...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,646389,Plane,"[Action, Adventure, Thriller]",After a heroic job of successfully landing his...,Gerard Butler-Mike Colter-Yoson An-Tony Goldwy...,"[pilot, airplane, philippines, held hostage, p...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,315162,Puss in Boots: The Last Wish,"[Animation, Adventure, Comedy, Family]",Puss in Boots discovers that his passion for a...,Antonio Banderas-Salma Hayek-Harvey Guillén-Wa...,"[fairy tale, talking dog, spin off, aftercredi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,505642,Black Panther: Wakanda Forever,"[Action, Adventure, Science Fiction]",Queen Ramonda Shuri M’Baku Okoye and the Dora ...,Letitia Wright-Lupita Nyong'o-Danai Gurira-Win...,"[loss of loved one, hero, sequel, superhero, b...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,956101,The Eighth Clause,[Thriller],Kat and Borja appear to be a perfect couple bu...,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,[Random],"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,"[Adventure, Animation, Fantasy]",The Fellowship of the Ring embark on a journey...,Christopher Guard-William Squire-Michael Schol...,"[elves, dwarf, based on novel or book, mission]",[Random],Random
4996,30636,Luna,[Drama],While touring in Italy a recently-widowed Amer...,Jill Clayburgh-Matthew Barry-Veronica Lazăr-Re...,"[italy, parent child relationship, heroin, div...",[Random],Random
4997,793,Blue Velvet,"[Drama, Crime, Mystery, Thriller]",The discovery of a severed human ear found in ...,Kyle MacLachlan-Isabella Rossellini-Dennis Hop...,"[sexual obsession, detective, small town, drug...",[Random],Random
4998,11021,Titanic,"[Action, Drama, History]",This little-known German film retells the true...,Sybille Schmitz-Hans Nielsen-Kirsten Heiberg-K...,"[sea, captain, passenger, cruise, iceberg, tit...",[Random],Random
4999,706774,Hope of Breast,[Romance],Yoshikawa Aimi refused to sleep with her husba...,Aimi Yoshikawa,[softcore],[Random],Random

In [26]:
def fetchDirector(obj):
    if obj == np.nan or obj == "Random":
        return list(("Random",))
    else:
        l = []
        counter = 0
        for i in ast.literal_eval(obj):
           if i["job"]== "Director":
               l.append(i["name"])
               break
        return l

In [27]:
movies_df["Director"] = movies_df["crew"].apply(fetchDirector)

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\1929771585.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["Director"] = movies_df["crew"].apply(fetchDirector)

In [28]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew,Director
0,631842,Knock at the Cabin,"[Horror, Mystery, Thriller]",While vacationing at a remote cabin a young gi...,Dave Bautista-Jonathan Groff-Ben Aldridge-Kris...,"[based on novel or book, sacrifice, cabin, fai...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",[James Cameron]
1,646389,Plane,"[Action, Adventure, Thriller]",After a heroic job of successfully landing his...,Gerard Butler-Mike Colter-Yoson An-Tony Goldwy...,"[pilot, airplane, philippines, held hostage, p...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",[Gore Verbinski]
2,315162,Puss in Boots: The Last Wish,"[Animation, Adventure, Comedy, Family]",Puss in Boots discovers that his passion for a...,Antonio Banderas-Salma Hayek-Harvey Guillén-Wa...,"[fairy tale, talking dog, spin off, aftercredi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",[Sam Mendes]
3,505642,Black Panther: Wakanda Forever,"[Action, Adventure, Science Fiction]",Queen Ramonda Shuri M’Baku Okoye and the Dora ...,Letitia Wright-Lupita Nyong'o-Danai Gurira-Win...,"[loss of loved one, hero, sequel, superhero, b...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",[Christopher Nolan]
4,956101,The Eighth Clause,[Thriller],Kat and Borja appear to be a perfect couple bu...,Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,[Random],"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",[Andrew Stanton]
...,...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,"[Adventure, Animation, Fantasy]",The Fellowship of the Ring embark on a journey...,Christopher Guard-William Squire-Michael Schol...,"[elves, dwarf, based on novel or book, mission]",[Random],Random,[Random]
4996,30636,Luna,[Drama],While touring in Italy a recently-widowed Amer...,Jill Clayburgh-Matthew Barry-Veronica Lazăr-Re...,"[italy, parent child relationship, heroin, div...",[Random],Random,[Random]
4997,793,Blue Velvet,"[Drama, Crime, Mystery, Thriller]",The discovery of a severed human ear found in ...,Kyle MacLachlan-Isabella Rossellini-Dennis Hop...,"[sexual obsession, detective, small town, drug...",[Random],Random,[Random]
4998,11021,Titanic,"[Action, Drama, History]",This little-known German film retells the true...,Sybille Schmitz-Hans Nielsen-Kirsten Heiberg-K...,"[sea, captain, passenger, cruise, iceberg, tit...",[Random],Random,[Random]
4999,706774,Hope of Breast,[Romance],Yoshikawa Aimi refused to sleep with her husba...,Aimi Yoshikawa,[softcore],[Random],Random,[Random]

In [29]:
movies_df["overview"][0]

'While vacationing at a remote cabin a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world the family must decide what they believe before all is lost.'

In [30]:
movies_df["overview"] = movies_df["overview"].str.split()

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3666493077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["overview"] = movies_df["overview"].str.split()

In [31]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew,Director
0,631842,Knock at the Cabin,"[Horror, Mystery, Thriller]","[While, vacationing, at, a, remote, cabin, a, ...",Dave Bautista-Jonathan Groff-Ben Aldridge-Kris...,"[based on novel or book, sacrifice, cabin, fai...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",[James Cameron]
1,646389,Plane,"[Action, Adventure, Thriller]","[After, a, heroic, job, of, successfully, land...",Gerard Butler-Mike Colter-Yoson An-Tony Goldwy...,"[pilot, airplane, philippines, held hostage, p...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",[Gore Verbinski]
2,315162,Puss in Boots: The Last Wish,"[Animation, Adventure, Comedy, Family]","[Puss, in, Boots, discovers, that, his, passio...",Antonio Banderas-Salma Hayek-Harvey Guillén-Wa...,"[fairy tale, talking dog, spin off, aftercredi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",[Sam Mendes]
3,505642,Black Panther: Wakanda Forever,"[Action, Adventure, Science Fiction]","[Queen, Ramonda, Shuri, M’Baku, Okoye, and, th...",Letitia Wright-Lupita Nyong'o-Danai Gurira-Win...,"[loss of loved one, hero, sequel, superhero, b...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",[Christopher Nolan]
4,956101,The Eighth Clause,[Thriller],"[Kat, and, Borja, appear, to, be, a, perfect, ...",Maite Perroni-Manuel Vega-Óscar Jaenada-Jessic...,[Random],"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",[Andrew Stanton]
...,...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,"[Adventure, Animation, Fantasy]","[The, Fellowship, of, the, Ring, embark, on, a...",Christopher Guard-William Squire-Michael Schol...,"[elves, dwarf, based on novel or book, mission]",[Random],Random,[Random]
4996,30636,Luna,[Drama],"[While, touring, in, Italy, a, recently-widowe...",Jill Clayburgh-Matthew Barry-Veronica Lazăr-Re...,"[italy, parent child relationship, heroin, div...",[Random],Random,[Random]
4997,793,Blue Velvet,"[Drama, Crime, Mystery, Thriller]","[The, discovery, of, a, severed, human, ear, f...",Kyle MacLachlan-Isabella Rossellini-Dennis Hop...,"[sexual obsession, detective, small town, drug...",[Random],Random,[Random]
4998,11021,Titanic,"[Action, Drama, History]","[This, little-known, German, film, retells, th...",Sybille Schmitz-Hans Nielsen-Kirsten Heiberg-K...,"[sea, captain, passenger, cruise, iceberg, tit...",[Random],Random,[Random]
4999,706774,Hope of Breast,[Romance],"[Yoshikawa, Aimi, refused, to, sleep, with, he...",Aimi Yoshikawa,[softcore],[Random],Random,[Random]

In [32]:
movies_df["credits"] = movies_df["credits"].str.split('-')

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3840310376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["credits"] = movies_df["credits"].str.split('-')

In [33]:
movies_df["credits"]

0       [Dave Bautista, Jonathan Groff, Ben Aldridge, ...
1       [Gerard Butler, Mike Colter, Yoson An, Tony Go...
2       [Antonio Banderas, Salma Hayek, Harvey Guillén...
3       [Letitia Wright, Lupita Nyong'o, Danai Gurira,...
4       [Maite Perroni, Manuel Vega, Óscar Jaenada, Je...
                              ...
4995    [Christopher Guard, William Squire, Michael Sc...
4996    [Jill Clayburgh, Matthew Barry, Veronica Lazăr...
4997    [Kyle MacLachlan, Isabella Rossellini, Dennis ...
4998    [Sybille Schmitz, Hans Nielsen, Kirsten Heiber...
4999                                     [Aimi Yoshikawa]
Name: credits, Length: 5000, dtype: object

In [34]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew,Director
0,631842,Knock at the Cabin,"[Horror, Mystery, Thriller]","[While, vacationing, at, a, remote, cabin, a, ...","[Dave Bautista, Jonathan Groff, Ben Aldridge, ...","[based on novel or book, sacrifice, cabin, fai...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",[James Cameron]
1,646389,Plane,"[Action, Adventure, Thriller]","[After, a, heroic, job, of, successfully, land...","[Gerard Butler, Mike Colter, Yoson An, Tony Go...","[pilot, airplane, philippines, held hostage, p...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",[Gore Verbinski]
2,315162,Puss in Boots: The Last Wish,"[Animation, Adventure, Comedy, Family]","[Puss, in, Boots, discovers, that, his, passio...","[Antonio Banderas, Salma Hayek, Harvey Guillén...","[fairy tale, talking dog, spin off, aftercredi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",[Sam Mendes]
3,505642,Black Panther: Wakanda Forever,"[Action, Adventure, Science Fiction]","[Queen, Ramonda, Shuri, M’Baku, Okoye, and, th...","[Letitia Wright, Lupita Nyong'o, Danai Gurira,...","[loss of loved one, hero, sequel, superhero, b...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",[Christopher Nolan]
4,956101,The Eighth Clause,[Thriller],"[Kat, and, Borja, appear, to, be, a, perfect, ...","[Maite Perroni, Manuel Vega, Óscar Jaenada, Je...",[Random],"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",[Andrew Stanton]
...,...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,"[Adventure, Animation, Fantasy]","[The, Fellowship, of, the, Ring, embark, on, a...","[Christopher Guard, William Squire, Michael Sc...","[elves, dwarf, based on novel or book, mission]",[Random],Random,[Random]
4996,30636,Luna,[Drama],"[While, touring, in, Italy, a, recently-widowe...","[Jill Clayburgh, Matthew Barry, Veronica Lazăr...","[italy, parent child relationship, heroin, div...",[Random],Random,[Random]
4997,793,Blue Velvet,"[Drama, Crime, Mystery, Thriller]","[The, discovery, of, a, severed, human, ear, f...","[Kyle MacLachlan, Isabella Rossellini, Dennis ...","[sexual obsession, detective, small town, drug...",[Random],Random,[Random]
4998,11021,Titanic,"[Action, Drama, History]","[This, little-known, German, film, retells, th...","[Sybille Schmitz, Hans Nielsen, Kirsten Heiber...","[sea, captain, passenger, cruise, iceberg, tit...",[Random],Random,[Random]
4999,706774,Hope of Breast,[Romance],"[Yoshikawa, Aimi, refused, to, sleep, with, he...",[Aimi Yoshikawa],[softcore],[Random],Random,[Random]

In [35]:
movies_df["genres"] = movies_df["genres"].apply(lambda x : [i.replace(' ', '') for i in x])
movies_df["keywords"] = movies_df["keywords"].apply(lambda x : [i.replace(' ', '') for i in x])
movies_df["cast"] = movies_df["cast"].apply(lambda x : [i.replace(' ', '') for i in x])
movies_df["Director"] = movies_df["Director"].apply(lambda x : [i.replace(' ', '') for i in x])
movies_df["credits"] = movies_df["credits"].apply(lambda x : [i.replace(' ', '') for i in x])

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3371381009.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["genres"] = movies_df["genres"].apply(lambda x : [i.replace(' ', '') for i in x])
C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3371381009.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["keywords"] = movies_df["keywords"].apply(lambda x : [i.replace(' ', '') for i in x])
C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3371381009.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["cast"] = movies_df["cast"].apply(lambda x : [i.replace(' ', '') for i in x])
C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3371381009.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["Director"] = movies_df["Director"].apply(lambda x : [i.replace(' ', '') for i in x])
C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3371381009.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["credits"] = movies_df["credits"].apply(lambda x : [i.replace(' ', '') for i in x])

In [36]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew,Director
0,631842,Knock at the Cabin,"[Horror, Mystery, Thriller]","[While, vacationing, at, a, remote, cabin, a, ...","[DaveBautista, JonathanGroff, BenAldridge, Kri...","[basedonnovelorbook, sacrifice, cabin, faith, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",[JamesCameron]
1,646389,Plane,"[Action, Adventure, Thriller]","[After, a, heroic, job, of, successfully, land...","[GerardButler, MikeColter, YosonAn, TonyGoldwy...","[pilot, airplane, philippines, heldhostage, pl...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",[GoreVerbinski]
2,315162,Puss in Boots: The Last Wish,"[Animation, Adventure, Comedy, Family]","[Puss, in, Boots, discovers, that, his, passio...","[AntonioBanderas, SalmaHayek, HarveyGuillén, W...","[fairytale, talkingdog, spinoff, aftercreditss...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",[SamMendes]
3,505642,Black Panther: Wakanda Forever,"[Action, Adventure, ScienceFiction]","[Queen, Ramonda, Shuri, M’Baku, Okoye, and, th...","[LetitiaWright, LupitaNyong'o, DanaiGurira, Wi...","[lossoflovedone, hero, sequel, superhero, base...","[ChristianBale, MichaelCaine, GaryOldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",[ChristopherNolan]
4,956101,The Eighth Clause,[Thriller],"[Kat, and, Borja, appear, to, be, a, perfect, ...","[MaitePerroni, ManuelVega, ÓscarJaenada, Jessi...",[Random],"[TaylorKitsch, LynnCollins, SamanthaMorton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",[AndrewStanton]
...,...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,"[Adventure, Animation, Fantasy]","[The, Fellowship, of, the, Ring, embark, on, a...","[ChristopherGuard, WilliamSquire, MichaelSchol...","[elves, dwarf, basedonnovelorbook, mission]",[Random],Random,[Random]
4996,30636,Luna,[Drama],"[While, touring, in, Italy, a, recently-widowe...","[JillClayburgh, MatthewBarry, VeronicaLazăr, R...","[italy, parentchildrelationship, heroin, diva,...",[Random],Random,[Random]
4997,793,Blue Velvet,"[Drama, Crime, Mystery, Thriller]","[The, discovery, of, a, severed, human, ear, f...","[KyleMacLachlan, IsabellaRossellini, DennisHop...","[sexualobsession, detective, smalltown, drugde...",[Random],Random,[Random]
4998,11021,Titanic,"[Action, Drama, History]","[This, little-known, German, film, retells, th...","[SybilleSchmitz, HansNielsen, KirstenHeiberg, ...","[sea, captain, passenger, cruise, iceberg, tit...",[Random],Random,[Random]
4999,706774,Hope of Breast,[Romance],"[Yoshikawa, Aimi, refused, to, sleep, with, he...",[AimiYoshikawa],[softcore],[Random],Random,[Random]

In [37]:
movies_df["tags"] = movies_df["genres"] + movies_df["overview"] + movies_df["keywords"] + movies_df["cast"] + movies_df["Director"] + movies_df["credits"]

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\3880812560.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df["tags"] = movies_df["genres"] + movies_df["overview"] + movies_df["keywords"] + movies_df["cast"] + movies_df["Director"] + movies_df["credits"]

In [38]:
movies_df

,id,title,genres,overview,credits,keywords,cast,crew,Director,tags
0,631842,Knock at the Cabin,"[Horror, Mystery, Thriller]","[While, vacationing, at, a, remote, cabin, a, ...","[DaveBautista, JonathanGroff, BenAldridge, Kri...","[basedonnovelorbook, sacrifice, cabin, faith, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",[JamesCameron],"[Horror, Mystery, Thriller, While, vacationing..."
1,646389,Plane,"[Action, Adventure, Thriller]","[After, a, heroic, job, of, successfully, land...","[GerardButler, MikeColter, YosonAn, TonyGoldwy...","[pilot, airplane, philippines, heldhostage, pl...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",[GoreVerbinski],"[Action, Adventure, Thriller, After, a, heroic..."
2,315162,Puss in Boots: The Last Wish,"[Animation, Adventure, Comedy, Family]","[Puss, in, Boots, discovers, that, his, passio...","[AntonioBanderas, SalmaHayek, HarveyGuillén, W...","[fairytale, talkingdog, spinoff, aftercreditss...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",[SamMendes],"[Animation, Adventure, Comedy, Family, Puss, i..."
3,505642,Black Panther: Wakanda Forever,"[Action, Adventure, ScienceFiction]","[Queen, Ramonda, Shuri, M’Baku, Okoye, and, th...","[LetitiaWright, LupitaNyong'o, DanaiGurira, Wi...","[lossoflovedone, hero, sequel, superhero, base...","[ChristianBale, MichaelCaine, GaryOldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",[ChristopherNolan],"[Action, Adventure, ScienceFiction, Queen, Ram..."
4,956101,The Eighth Clause,[Thriller],"[Kat, and, Borja, appear, to, be, a, perfect, ...","[MaitePerroni, ManuelVega, ÓscarJaenada, Jessi...",[Random],"[TaylorKitsch, LynnCollins, SamanthaMorton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",[AndrewStanton],"[Thriller, Kat, and, Borja, appear, to, be, a,..."
...,...,...,...,...,...,...,...,...,...,...
4995,123,The Lord of the Rings,"[Adventure, Animation, Fantasy]","[The, Fellowship, of, the, Ring, embark, on, a...","[ChristopherGuard, WilliamSquire, MichaelSchol...","[elves, dwarf, basedonnovelorbook, mission]",[Random],Random,[Random],"[Adventure, Animation, Fantasy, The, Fellowshi..."
4996,30636,Luna,[Drama],"[While, touring, in, Italy, a, recently-widowe...","[JillClayburgh, MatthewBarry, VeronicaLazăr, R...","[italy, parentchildrelationship, heroin, diva,...",[Random],Random,[Random],"[Drama, While, touring, in, Italy, a, recently..."
4997,793,Blue Velvet,"[Drama, Crime, Mystery, Thriller]","[The, discovery, of, a, severed, human, ear, f...","[KyleMacLachlan, IsabellaRossellini, DennisHop...","[sexualobsession, detective, smalltown, drugde...",[Random],Random,[Random],"[Drama, Crime, Mystery, Thriller, The, discove..."
4998,11021,Titanic,"[Action, Drama, History]","[This, little-known, German, film, retells, th...","[SybilleSchmitz, HansNielsen, KirstenHeiberg, ...","[sea, captain, passenger, cruise, iceberg, tit...",[Random],Random,[Random],"[Action, Drama, History, This, little-known, G..."
4999,706774,Hope of Breast,[Romance],"[Yoshikawa, Aimi, refused, to, sleep, with, he...",[AimiYoshikawa],[softcore],[Random],Random,[Random],"[Romance, Yoshikawa, Aimi, refused, to, sleep,..."

In [39]:
movies_df_final = movies_df[["id", "title", "tags"]]

In [40]:
movies_df_final

,id,title,tags
0,631842,Knock at the Cabin,"[Horror, Mystery, Thriller, While, vacationing..."
1,646389,Plane,"[Action, Adventure, Thriller, After, a, heroic..."
2,315162,Puss in Boots: The Last Wish,"[Animation, Adventure, Comedy, Family, Puss, i..."
3,505642,Black Panther: Wakanda Forever,"[Action, Adventure, ScienceFiction, Queen, Ram..."
4,956101,The Eighth Clause,"[Thriller, Kat, and, Borja, appear, to, be, a,..."
...,...,...,...
4995,123,The Lord of the Rings,"[Adventure, Animation, Fantasy, The, Fellowshi..."
4996,30636,Luna,"[Drama, While, touring, in, Italy, a, recently..."
4997,793,Blue Velvet,"[Drama, Crime, Mystery, Thriller, The, discove..."
4998,11021,Titanic,"[Action, Drama, History, This, little-known, G..."
4999,706774,Hope of Breast,"[Romance, Yoshikawa, Aimi, refused, to, sleep,..."

In [41]:
movies_df_final["tags"] = movies_df_final["tags"].apply(lambda x: " ".join(x))

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\980407454.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df_final["tags"] = movies_df_final["tags"].apply(lambda x: " ".join(x))

In [42]:
movies_df_final

,id,title,tags
0,631842,Knock at the Cabin,Horror Mystery Thriller While vacationing at a...
1,646389,Plane,Action Adventure Thriller After a heroic job o...
2,315162,Puss in Boots: The Last Wish,Animation Adventure Comedy Family Puss in Boot...
3,505642,Black Panther: Wakanda Forever,Action Adventure ScienceFiction Queen Ramonda ...
4,956101,The Eighth Clause,Thriller Kat and Borja appear to be a perfect ...
...,...,...,...
4995,123,The Lord of the Rings,Adventure Animation Fantasy The Fellowship of ...
4996,30636,Luna,Drama While touring in Italy a recently-widowe...
4997,793,Blue Velvet,Drama Crime Mystery Thriller The discovery of ...
4998,11021,Titanic,Action Drama History This little-known German ...
4999,706774,Hope of Breast,Romance Yoshikawa Aimi refused to sleep with h...

In [43]:
movies_df_final["tags"] = movies_df_final["tags"].apply(lambda x: x.lower())

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\1703548524.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df_final["tags"] = movies_df_final["tags"].apply(lambda x: x.lower())

In [44]:
movies_df_final

,id,title,tags
0,631842,Knock at the Cabin,horror mystery thriller while vacationing at a...
1,646389,Plane,action adventure thriller after a heroic job o...
2,315162,Puss in Boots: The Last Wish,animation adventure comedy family puss in boot...
3,505642,Black Panther: Wakanda Forever,action adventure sciencefiction queen ramonda ...
4,956101,The Eighth Clause,thriller kat and borja appear to be a perfect ...
...,...,...,...
4995,123,The Lord of the Rings,adventure animation fantasy the fellowship of ...
4996,30636,Luna,drama while touring in italy a recently-widowe...
4997,793,Blue Velvet,drama crime mystery thriller the discovery of ...
4998,11021,Titanic,action drama history this little-known german ...
4999,706774,Hope of Breast,romance yoshikawa aimi refused to sleep with h...

In [45]:
movies_df_final["tags"] = movies_df_final["tags"].apply(lambda x: x.replace("random", ''))

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\2131513514.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df_final["tags"] = movies_df_final["tags"].apply(lambda x: x.replace("random", ''))

In [46]:
movies_df_final

,id,title,tags
0,631842,Knock at the Cabin,horror mystery thriller while vacationing at a...
1,646389,Plane,action adventure thriller after a heroic job o...
2,315162,Puss in Boots: The Last Wish,animation adventure comedy family puss in boot...
3,505642,Black Panther: Wakanda Forever,action adventure sciencefiction queen ramonda ...
4,956101,The Eighth Clause,thriller kat and borja appear to be a perfect ...
...,...,...,...
4995,123,The Lord of the Rings,adventure animation fantasy the fellowship of ...
4996,30636,Luna,drama while touring in italy a recently-widowe...
4997,793,Blue Velvet,drama crime mystery thriller the discovery of ...
4998,11021,Titanic,action drama history this little-known german ...
4999,706774,Hope of Breast,romance yoshikawa aimi refused to sleep with h...

In [47]:
from nltk.stem.porter import PorterStemmer

In [48]:
ps = PorterStemmer()

In [49]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [50]:
movies_df_final.shape

(5000, 3)

In [51]:
movies_df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      5000 non-null   int64
 1   title   5000 non-null   object
 2   tags    5000 non-null   object
dtypes: int64(1), object(2)
memory usage: 117.3+ KB

In [52]:
movies_df_final["tags"] = movies_df_final["tags"].apply(stem)

C:\Users\Kr. SOURAV\AppData\Local\Temp\ipykernel_11832\2638666776.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df_final["tags"] = movies_df_final["tags"].apply(stem)

In [53]:
movies_df_final

,id,title,tags
0,631842,Knock at the Cabin,horror mysteri thriller while vacat at a remot...
1,646389,Plane,action adventur thriller after a heroic job of...
2,315162,Puss in Boots: The Last Wish,anim adventur comedi famili puss in boot disco...
3,505642,Black Panther: Wakanda Forever,action adventur sciencefict queen ramonda shur...
4,956101,The Eighth Clause,thriller kat and borja appear to be a perfect ...
...,...,...,...
4995,123,The Lord of the Rings,adventur anim fantasi the fellowship of the ri...
4996,30636,Luna,drama while tour in itali a recently-widow ame...
4997,793,Blue Velvet,drama crime mysteri thriller the discoveri of ...
4998,11021,Titanic,action drama histori thi little-known german f...
4999,706774,Hope of Breast,romanc yoshikawa aimi refus to sleep with her ...

In [54]:
from sklearn.feature_extraction.text import CountVectorizer

In [55]:
cv = CountVectorizer(max_features=5000, stop_words="english")

In [56]:
vectors = cv.fit_transform(movies_df_final["tags"]).toarray()

In [57]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [58]:
cv.get_feature_names_out()

array(['10', '11', '12', ..., 'zooeydeschanel', 'zoëkravitz',
       'ólafurdarriólafsson'], dtype=object)

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
similarity = cosine_similarity(vectors)

In [61]:
similarity.shape

(5000, 5000)

In [62]:
similarity

array([[1.        , 0.02652791, 0.08247861, ..., 0.08817334, 0.02486824,
        0.02317449],
       [0.02652791, 1.        , 0.13401407, ..., 0.02865341, 0.06465082,
        0.        ],
       [0.08247861, 0.13401407, 1.        , ..., 0.        , 0.        ,
        0.02341465],
       ...,
       [0.08817334, 0.02865341, 0.        , ..., 1.        , 0.02686077,
        0.02503131],
       [0.02486824, 0.06465082, 0.        , ..., 0.02686077, 1.        ,
        0.02823912],
       [0.02317449, 0.        , 0.02341465, ..., 0.02503131, 0.02823912,
        1.        ]])

In [63]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x:x[1])[1:6]

[(4895, 0.282842712474619),
 (4466, 0.23328473740792172),
 (82, 0.23169450252912405),
 (1784, 0.2287545054358387),
 (762, 0.22587697572631282)]

In [64]:
def recommend(movie):
    movie_index = movies_df_final[movies_df_final["title"] == movie].index
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances[0])), reverse=True, key=lambda x:x[1])[1:6]
    for i in movie_list:
        # print(movies_df_final.iloc[i[0]]["title"])
        print(i)
        print(movies_df_final.iloc[i[0]]["id"])

In [65]:
recommend("Avatar")

(1362, 0.3932841152066773)
216527
(1938, 0.38332593899996387)
393209
(1684, 0.34992710611188255)
83533
(12, 0.3306500356330541)
76600
(1191, 0.24489795918367344)
44943

In [66]:
import pickle

In [68]:
pickle.dump(movies_df_final, open("movies.pkl", "wb"))

In [69]:
pickle.dump(similarity, open("similarity.pkl", "wb"))